import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Mode from "@/components/Mode";
import Background from "@/components/Background";
import  AppContext  from "@/context/appContext";

const josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "My todo app",
  description: "Generated by create next app",
  icons: '/images/bg-desktop-light.jpg'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefin.className} relative w-screen h-screen `} >
        <AppContext>
        <Background/>

        <div className="absolute top-[4.2rem] left-1/2 -translate-x-1/2 max-w-[50rem] mx-auto w-1/3 max-lg:w-2/4 max-md:w-3/4 max-sm:w-5/6 max-[500px]: h-[400px]">

          <div className="flex justify-between text-white">
            <div className="tracking-[1rem] font-bold text-2xl">TODO</div>
            <Mode/>
          </div>

          {children}
        </div>
        </AppContext>
        </body>
    </html>
  );
}
